### ISSUE TITLE
动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by V1rtu0l** [0xlane/ollvm-rust#1]
如图，大佬，这个我按照例子使用无法正常编译，是啥原因呢
![image](https://github.com/user-attachments/assets/c55ec5d3-a727-4784-82f3-ee7ad59e1c1e)

**Comment by 0xlane** [comment]
这种情况一般是vc运行时环境问题，release里编译的那个dll依赖msvcp140.dll、vcruntime140.dll、vcruntime140_1.dll

**Comment by 0xlane** [comment]
到 https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170 下载vc运行时安装就可以了
